[tool.poetry]
name = "schedule-parser"
version = "0.1.0"
description = "Stankin Schedule PDF Parser"
authors = ["PROF-Development"]
readme = "README.md"
homepage = "https://github.com/PROF-Development/schedule-parser"
repository = "https://github.com/PROF-Development/schedule-parser.git"
packages = [
    { include = "schedule_parser" }
]

[tool.poetry.dependencies]
python = "^3.12"
pdfplumber = "^0.10.2"
pydantic = "^2.5.2"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
